name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    steps:
      - name: Checkout code # 步骤名称
        uses: actions/checkout@v4 # 使用GitHub官方的checkout操作获取代码

      - name: Set up Go
        uses: actions/setup-go@v5 # 设置Go环境
        with:
          go-version: 1.22.x # 指定Go的版本

      - name: Install dependencies
        run: go mod download
