name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    steps:
      - name: Checkout code # 步骤名称
        uses: actions/checkout@v4 # 使用GitHub官方的checkout操作获取代码

      - name: Set outputs
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5 # 设置Go环境
        with:
          go-version: 1.22.x # 指定Go的版本


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.fuckout.work:8443/temp/test-action

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: harbor.fuckout.work:8443
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
